resources:
  - name: gitRepo_code
    type: GitRepo
    configuration:
      path: jefferyfry/aws-modernization-with-jfrog
      gitProvider: GitHub
      branches:
        include: master
  - name: npmBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: npm_build
      buildNumber: ${run_number}

  - name: scanned_npmBuild_Info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: npm_build
      buildNumber: ${run_number}
      
  - name: promoted_npmBuild_Info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: npm_build
      buildNumber: ${run_number}
      
      
  - name: docker_npmBuild_Info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: npm_build
      buildNumber: ${run_number}
   
   
  - name: scanned_npm_dockerBuild_Info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: npm_build
      buildNumber: ${run_number}


  - name: promoted_docker_npmBuild_Info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: npm_build
      buildNumber: ${run_number}  
      
  - name: final_docker_npmBuild_Info 
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: npm_build
      buildNumber: ${run_number}    
      
      

      
pipelines:
  - name: init_jfrog
    steps:
    - name: create_scaffolding
      type: Bash
      configuration:
       inputResources:
        - name: gitRepo_code
          trigger: false
       integrations:
        - name: Artifactory
      execution:
       onStart:
        - sudo apt-get install -y haveged
        - sudo service haveged start 
        - curl -fL https://getcli.jfrog.io | sh
        - sudo apt-get install -y jq
        - cp jfrog  `which jfrog`
        - retry_command jfrog rt config --url $int_Artifactory_url --user
          $int_Artifactory_user --apikey $int_Artifactory_apikey
          --interactive=false
        - "cd ${res_gitRepo_code_resourcePath}"
        - "./scripts/create_entities.sh"
